version: "3.9"
services:
  nginx:
    container_name: nginx_service
    image: "nginx:1.20.1-alpine"
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./.nginx:/etc/nginx/conf.d"
      - "./.certs:/etc/ssl/private"
      - ".:/usr/share/nginx/html"
    restart: unless-stopped
